name: Daily Dashboard Update

on:
  schedule:
    # 毎日 日本時間 9:00 (UTC 0:00) に実行
    - cron: '0 0 * * *'
  workflow_dispatch: # 手動実行ボタンも有効化

jobs:
  trigger_amplify_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify Build
        run: |
          # ここにAmplifyのWebhook URLを貼り付けてください
          # 例: curl -X POST -d {} "https://webhooks.amplify.us-east-1.amazonaws.com/..."
          
          curl -X POST -d {} "https://webhooks.amplify.ap-northeast-1.amazonaws.com/prod/webhooks?id=0ab8d815-4a53-4223-bd0d-1e25fada5949&token=gwQc1ivxX0N7plYqfcpZ8UFglJyauNiPIMxj6VRcgu4"
